"""initial schema

Revision ID: 44d6f2054b79
Revises: 
Create Date: 2026-07-13 10:33:56.797936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44d6f2054b79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_url', sa.String(length=512), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('webhook_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_created_at'), 'repository', ['created_at'], unique=False)
    op.create_index(op.f('ix_repository_repo_name'), 'repository', ['repo_name'], unique=False)
    op.create_table('pullrequest',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('base_branch', sa.String(length=255), nullable=False),
    sa.Column('head_branch', sa.String(length=255), nullable=False),
    sa.Column('pr_url', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'MERGED', name='prstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pullrequest_created_at'), 'pullrequest', ['created_at'], unique=False)
    op.create_index(op.f('ix_pullrequest_pr_number'), 'pullrequest', ['pr_number'], unique=False)
    op.create_index(op.f('ix_pullrequest_status'), 'pullrequest', ['status'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pr_id', sa.UUID(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'CHANGES_REQUESTED', 'COMMENTED', name='reviewdecision', native_enum=False), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('security_count', sa.Integer(), nullable=False),
    sa.Column('quality_count', sa.Integer(), nullable=False),
    sa.Column('logic_count', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=False),
    sa.Column('human_override', sa.Boolean(), nullable=False),
    sa.Column('override_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pr_id'], ['pullrequest.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decision'), 'review', ['decision'], unique=False)
    op.create_index(op.f('ix_review_reviewed_at'), 'review', ['reviewed_at'], unique=False)
    op.create_table('reviewcomment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('comment_type', sa.Enum('BUG', 'STYLE', 'SECURITY', 'PERFORMANCE', 'DOCUMENTATION', name='commenttype', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='severity', native_enum=False), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('github_comment_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewcomment_created_at'), 'reviewcomment', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviewcomment_created_at'), table_name='reviewcomment')
    op.drop_table('reviewcomment')
    op.drop_index(op.f('ix_review_reviewed_at'), table_name='review')
    op.drop_index(op.f('ix_review_decision'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_pullrequest_status'), table_name='pullrequest')
    op.drop_index(op.f('ix_pullrequest_pr_number'), table_name='pullrequest')
    op.drop_index(op.f('ix_pullrequest_created_at'), table_name='pullrequest')
    op.drop_table('pullrequest')
    op.drop_index(op.f('ix_repository_repo_name'), table_name='repository')
    op.drop_index(op.f('ix_repository_created_at'), table_name='repository')
    op.drop_table('repository')
    # ### end Alembic commands ###
