"""Add GitHub Review Publishing fields final

Revision ID: 8ecadc60265a
Revises: 44d6f2054b79
Create Date: 2026-07-13 18:08:49.634057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ecadc60265a'
down_revision: Union[str, Sequence[str], None] = '44d6f2054b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('github_review_id', sa.String(length=255), nullable=True))
    op.add_column('review', sa.Column('publishing_status', sa.String(length=50), server_default='PENDING', nullable=False))
    op.add_column('review', sa.Column('publishing_timestamp', sa.DateTime(), nullable=True))
    op.add_column('review', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'retry_count')
    op.drop_column('review', 'publishing_timestamp')
    op.drop_column('review', 'publishing_status')
    op.drop_column('review', 'github_review_id')
    # ### end Alembic commands ###
